### ISSUE TITLE
Implementation of the 'info' button control

### ISSUE THREAD

**Issue by tim-rex** [supersaiyanmode/PyWebOSTV#10]
Some of the older LG televisions have an 'info' button on the remote control, that had been removed in recent models.

The same functionality is available via the LG TV Plus app, so it seems it should be a command we can issue in the same way..

Has anyone discovered the SSAP command to do that? Would be very helpful.
I imagine there is a whole lot of undocumented or otherwise unknown functionality using this API.. would love to explore this more!

**Comment by tim-rex** [comment]
Actually... never mind. I've worked it out.
Pull request in progress.

**Comment by supersaiyanmode** [comment]
Thanks so much @tim-rex! Looking forward to it. :+1:

**Comment by santhiyaattivo** [comment]
Hi @tim-rex ,

I tried INFO and it doesn't seem to work now. 
Any lead?
