### ISSUE TITLE
Energy Saving settings

### ISSUE THREAD

**Issue by jorlarsen** [supersaiyanmode/PyWebOSTV#104]
Hi, I just wondered if it is possible to change the energy saving settings (screen brightness) with this tool?

**Comment by supersaiyanmode** [comment]
I'm not aware of this setting being exposed by the TV (my information could very well be out of date). Please correct me if I'm wrong.

**Comment by jorlarsen** [comment]
Was able to do this using https://github.com/home-assistant/core/tree/dev/homeassistant/components/webostv :)
