### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by reizajudiz** [supersaiyanmode/PyWebOSTV#12]
>>> from pywebostv import connection
>>> client = connection.WebOSClient('IP')
>>> client.connect()

it give me error: [Errno 111] Connection refused
what should I check?

**Comment by Gustry** [comment]
Did you enable remote control over network on your TV?
Did you success to use the smartphone app?  (https://play.google.com/store/apps/details?id=com.lge.app1&hl=fr on Android)

**Comment by supersaiyanmode** [comment]
Once you have enabled remote control over network as @Gustry says, you can perhaps check if there's a anything listening on that IP and port number 3000.

**Comment by reizajudiz** [comment]
how to enable remote control over network?

**Comment by supersaiyanmode** [comment]
@reizajudiz See https://www.lg.com/uk/support/product-help/CT00008334-1437131798537-others

**Comment by reizajudiz** [comment]
http://webossignage.developer.lge.com/discover/webos-signage/discover-webos-signage/
maybe my signage version a bit different. I tried all possible menu but found nothing about remote control over network.
I'm using LG SIGNAGE SM5KD

**Comment by reizajudiz** [comment]
Nmap scan report for for LG SIGNAGE
Not shown: 992 closed ports
PORT      STATE SERVICE
80/tcp    open  http
443/tcp   open  https
2046/tcp  open  sdfunc
3737/tcp  open  xpanel
9080/tcp  open  glrpc
9998/tcp  open  distinct32
10000/tcp open  snet-sensor-mgmt
10002/tcp open  documentum
