### ISSUE TITLE
Wake On LAN easy add on

### ISSUE THREAD

**Issue by gschomburg** [supersaiyanmode/PyWebOSTV#13]
Thanks for this lib, it just saved me. I wanted to mention that adding a turn on functionality could be super handy. klattimer has example code in his project.

you can add wakonlan and then just -> send_magic_packet('tv:mac:address:here')
I think the tv also needs to be already paired and have its wake on lan setting turned on. Sometimes they hide this menu. I had to follow [these instructions](https://www.lg.com/in/support/product-help/CT32003428-20150309396894-others) to get the menu up. 
If I have time I'll fork and do a pull request

**Comment by Gustry** [comment]
If I'm correct, I didn't need to pair the remote with the TV to start the TV. You only need to enable WakeOnLan on the TV and then do a
`wakeonlan IP_ADDRESS`

But maybe I'm wrong, I don't have the TV right now to check.

**Comment by supersaiyanmode** [comment]
Hi @gschomburg I'm glad this library helped you! Just to confirm you are talking about WOL and not WOWLan, right? I don't think if the firmware supported it about 1 year back when I started writing this. If that has changed in the recent past and you feel it works reliably, please feel free to send a PR.
