### ISSUE TITLE
Get pause status or current timestamp

### ISSUE THREAD

**Issue by HudsonMC16** [supersaiyanmode/PyWebOSTV#20]
Thanks for the library. I like your implementation, it seems you put a lot of thought into its use, instead of just exposing all the functions, so thanks!

Is it possible to get the current pause/playing status of the foreground app, or even get the current media timestamp? Seems like it should exist, and I've been hunting, but I can't find any tool which allows this.

**Comment by supersaiyanmode** [comment]
Hi @HudsonMC16 You're welcome! As for the play status and timestamp -- I don't have access to an LG TV as of right now. But I can try to see if the TV supports it over this weekend. Just to be clear -- are you asking about TV native media player or external apps like Youtube?

**Comment by HudsonMC16** [comment]
Thanks for the quick reply @supersaiyanmode 

I suppose it would be either. I would have expected the get_current_app command to return information of that nature, but I'm not sure it does, based on the testing I've done. I'm pretty far outside of my element with this java stuff, though (which is why I was excited to stumble upon your python library).

**Comment by HudsonMC16** [comment]
Hey there, hate to pester, but was wondering if you were able to find any useful information on this? Even some command I don't know about, the response to which contains this information, would be helpful as I could branch and work from that.

**Comment by supersaiyanmode** [comment]
Sorry for the late response. AFAICT, it looks like there is no mechanism to get the time information from currently playing media. I haven't yet checked the ConnectSDK that I used to refer which writing this library. If it's supported there, it should not be too difficult to port here. If it's not supported, there's a (somewhat of a) good chance that WebOS doesn't expose the information.

Do you mind checking if there's an API exposed in [ConnectSDK](https://github.com/ConnectSDK/Connect-SDK-Android-Core/tree/master/src/com/connectsdk/service/webos)?

**Comment by HudsonMC16** [comment]
Hrmm, doesn't appear it's supported there: https://github.com/ConnectSDK/Connect-SDK-Android-Core/blob/master/src/com/connectsdk/service/webos/WebOSTVDeviceService.java#L748

**Comment by HudsonMC16** [comment]
but then this matrix on the connectsdk website indicates play state subscription is supported: http://connectsdk.com/SupportedFeatures/

**Comment by supersaiyanmode** [comment]
Hmm, interesting! May I ask you for a favor because I dont have an LG TV (that is unless I SSH around halfway around the globe and bother my family)?

Would you mind setting the attribute `"subscription": True,` on line 174 and 175 of controls.py (much like the one on line 162) and try subscribing to it (Readme has the Info on how to subscribe)? Once there, press play/pause on your phone  so see if that works.

**Comment by HudsonMC16** [comment]
No dice. Following code after those changes will show volume changes but not play/pause. I tried it in youtube and netflix: 
```
from pywebostv.discovery import *
from pywebostv.connection import *
from pywebostv.controls import *
import time
import yaml
import os

# key init
if 'store.yaml' in os.listdir():
    with open('store.yaml', 'rt') as file:
        store = yaml.safe_load(file)
else:
    store = {}

# connection
client = WebOSClient('192.168.50.208')
client.connect()
for status in client.register(store):
    if status == WebOSClient.PROMPTED:
        print("Please accept the connect on the TV!")
    elif status == WebOSClient.REGISTERED:
        print("Registration successful!")

# key storage
with open('store.yaml', 'wt') as file:
    yaml.safe_dump(store, file)

# callback class because I hate copy/paste
class callback():
    def __init__(self, type):
        self.type = type
    def callback(self, status, payload):
        if status:
            print(self.type, status, payload, sep='\n', end='\n\n')
        else:
            print(self.type, 'error', end='\n\n')

media = MediaControl(client)

on_play = callback('-PLAY-')
media.subscribe_play(on_play.callback)

on_pause = callback('-PAUSE-')
media.subscribe_pause(on_pause.callback)

on_volume = callback('-VOLUME-')
media.subscribe_get_volume(on_volume.callback)

time.sleep(10)
```

**Comment by supersaiyanmode** [comment]
That code looks about right. With your attempt and the general lack of documentation from LG, I'm inclined to say that perhaps the TV doesn't expose what you need.

**Comment by HudsonMC16** [comment]
Yeah. I was afraid of that. Thanks for looking into it!

**Comment by Gustry** [comment]
IIRC, in one android app (LG TV plus?), we can have access to this info, no?

**Comment by supersaiyanmode** [comment]
@Gustry Wow, I didn't know that! I have very little idea about Android development, but would a APK decompile lead us anywhere? Or may be snoop into WS traffic?

PS: I don't have an LG TV to try all of these out. :(

**Comment by Gustry** [comment]
https://play.google.com/store/apps/details?id=com.lge.app1

Look at the the 7th demo screenshot on the webpage, @HudsonMC16 is it what you want?

@supersaiyanmode It's the app I was using when I was at my parents home, where the LG tv is. It was working well. But there are others app for controlling the TV.

**Comment by HudsonMC16** [comment]
I downloaded that app this morning to try it out, and turns out that screenshot is misleading. That interface is only available when you're streaming media from your phone to the TV. When a TV app is being used, the app interface mirrors the hardware remote and all its buttons.

**Comment by supersaiyanmode** [comment]
@HudsonMC16 Thanks so much for confirming! IIRC, I saw a few Javascript SDKs with the media player API. I wanted to do that too, but at the moment I neither have the TV or time to take this on. I'd really appreciate PRs though :-)

**Comment by HudsonMC16** [comment]
What specifically did you want to add?

**Comment by supersaiyanmode** [comment]
Here is the list of [all potentially exposed APIs](http://webostv.developer.lge.com/api/webos-service-api/). I wanted to explore and find out if there are supported over our standard WS connection. For instance, the [volume control APIs](http://webostv.developer.lge.com/api/webos-service-api/audio/) look somewhat similar (URI Schema seems different ssap v/s luna). What I'd do is grab the URIs and methods from that page, create a new class that extends `WebOSControlBase`, populate `COMMANDS` based off of info on that page and check to see if that works..
