### ISSUE TITLE
Access to exit button?

### ISSUE THREAD

**Issue by brickfungus** [supersaiyanmode/PyWebOSTV#22]
I couldn't find anything in the code for using the exit button (keycode 412).  Is there a way to do that?

**Comment by supersaiyanmode** [comment]
Hi! Would you be able to test if https://github.com/supersaiyanmode/PyWebOSTV/pull/24 works for you? Thanks so much for your time!

**Comment by brickfungus** [comment]
I would love to.  Could you get the newest pushed out to pypi?

**Comment by supersaiyanmode** [comment]
I was hoping you'd perhaps want to test the latest source directly from this repo. If if works for you, I'd push it to PyPI so everyone can get it. (I'm unable to test it -- I don't have access to an LG TV right now).

Not entirely sure, but if you're looking for steps, they are below: 
```
$ source your_virtualenv/bin/activate
$ cd /tmp
$ git clone https://github.com/supersaiyanmode/PyWebOSTV
$ cd PyWebOSTV
$ python setup.py install
$ # You should now have the new exit button from #24 now.
```

Thanks again for your time and help!

**Comment by brickfungus** [comment]
Yea, I can do that.  Thanks

**Comment by brickfungus** [comment]
Confirmed exit button works!

**Comment by supersaiyanmode** [comment]
That is awesome! I'll push it out to PyPi very soon. Thanks for testing.

**Comment by supersaiyanmode** [comment]
Pushed it out to PyPI: https://pypi.org/manage/project/pywebostv/release/0.8.4/
