### ISSUE TITLE
Audio output selection

### ISSUE THREAD

**Issue by rcarmo** [supersaiyanmode/PyWebOSTV#27]
Hello there, 

I'm looking for a Python library that can support external output selection like https://github.com/merdok/homebridge-webos-tv/blob/master/index.js#L344 - I was wondering if this planned for (I can test/possibly contribute depending on time).

**Comment by supersaiyanmode** [comment]
If you mean audio output selection, then I don't think this library supports it as of now. However, it would be extremely straightforward to implement it. 

If you're willing to create a PR, I'd be happy to merge it in. :) Please look at a similar class: https://github.com/supersaiyanmode/PyWebOSTV/blob/e73438c4de9817bb98d8aa300a59cdaa218771c7/pywebostv/controls.py#L398

**Comment by rcarmo** [comment]
Hmmm. Nice. I hadn’t noticed that part of the code.

Besides the usual time constraints testing this is going to be tricky (can’t mess around with the TV most of the time), but I appreciate the pointer and will have a look at it.

**Comment by supersaiyanmode** [comment]
This was recently contributed by user Felix-Pi here: https://github.com/supersaiyanmode/PyWebOSTV/pull/43
