### ISSUE TITLE
Screen capture

### ISSUE THREAD

**Issue by tinkuad77** [supersaiyanmode/PyWebOSTV#31]
This is working like charm. Is there a way we can capture the image on tv? could you please help.

**Comment by engineerPapa** [comment]
Just wanted to check here, Is the team working on this requirement?

**Comment by supersaiyanmode** [comment]
Hi @engineerPapa, there is no team. Just a bunch of folks on the internet that use some of their free time towards this effort.

That being said, this repo is really a client library that knows how to talk to APIs being exposed by the TV. If the TV doesn't expose an API, there isn't much that this library can do. The last time I checked, WebOS doesn't expose an API that lets client capture a screenshot and stream the image back to them (most likely to stay compliant with copyright laws).

**Comment by engineerPapa** [comment]
Thanks @supersaiyanmode 
The folks have done a superb job to make life easy. Thanks!

Just a thought, Android Smart TV are supporting screen capture of screen obviously for DRM content we get a black screen.
That was the only reason just thought of checking.

**Comment by supersaiyanmode** [comment]
You're welcome :)

AFAICT, it looks like WebOS doesn't allow that functionality. If this isn't true, and there are documentations of this API or other libraries implementing screenshot -- let me know. I will try to implement it in this library too.

Closing this issue for now..
