### ISSUE TITLE
How to expand the list of api commands?

### ISSUE THREAD

**Issue by ifeech** [supersaiyanmode/PyWebOSTV#39]
I want to add commands. For example, turning on the TV.
I didn't find it in the documentation. Where can I see the entire list of teams?

**Comment by Gustry** [comment]
For turning the TV on, it's normal that it's not in the API. It's a wake on LAN command. https://github.com/supersaiyanmode/PyWebOSTV/issues/34

Which other command are you looking for?

**Comment by ifeech** [comment]
О, thanks friend! 
I want to now, how did you get the api commands? I have not found any information in the LV documentation about ssap://. Just luna://

And I didn't find any information about the handshake

**Comment by supersaiyanmode** [comment]
Hi @ifeech, it was tricky in the beginning. LG didn't share any documentation whatsoever. I had to do it the hard way -- read through ConnectSDK source (and other similar python projects whose authors undertook similar work) and port it to Python.

The Handshake portion was (IIRC) borrowed from LG Remote project (link in the main README.md).

**Comment by ifeech** [comment]
Thanks for your work
