### ISSUE TITLE
Any suggestions on WOL?

### ISSUE THREAD

**Issue by thevickypedia** [supersaiyanmode/PyWebOSTV#45]
I have the mac address of my TV and would like to turn it on remotely. I have used WOL tools for windows machines in the past but no idea on how to use a python program to do that on a TV. Any suggestions or guide would be much appreciated. Thanks in advance

**Comment by Gustry** [comment]
Any WOL library works. Look on pypi with "wol", for instance 
https://pypi.org/project/wakeonlan/

**Comment by thevickypedia** [comment]
This turns on the tv remotely
```
from wakeonlan import send_magic_packet
send_magic_packet('01:2E:45:67:89:10')  # dummy mac address
```
