### ISSUE TITLE
Some basic help?

### ISSUE THREAD

**Issue by jltnol** [supersaiyanmode/PyWebOSTV#56]
I am not a python guru, so please excuse my elemental questions. I'm trying to get all the files installed so I can control my LG TV via python scripts and Indigo Home Automation. 

I've read this works with Python 2.0, but does anyone know if it will work with Python 3.9?  If not, is it possible to have a dual install of 2 different versions of Python?

**Comment by sobertram** [comment]
you can have python 2.x and python3.x on the same system without conflicts.
when you need to use python3 type python3. same for pip, use pip3 for
python3.

There might be a way to change the system so that when you type python it
looks at python3 and not python2 but i am not sure.

**Comment by Gustry** [comment]
This project is compatible Python3, maybe the readme is not up to date.

I can't test with a TV right now, but I'm pretty sure.
Like https://github.com/supersaiyanmode/PyWebOSTV/commit/66873d7fa8391bf78f609430e1efe0e0b6587d71

**Comment by Gustry** [comment]
Each commits are tested again Python 2 and 3 at the same time : https://travis-ci.org/github/supersaiyanmode/PyWebOSTV/builds/752005129

**Comment by Gustry** [comment]
Very quick commit 22f2f19d8958d158a5dc41349212c4b56c6c8cce to keep track
