### ISSUE TITLE
Unable to connect to mouse exception

### ISSUE THREAD

**Issue by HanSooloo** [supersaiyanmode/PyWebOSTV#57]
Trying to do a simple connection where my app will send Enter/Click to the TV.    Why can I not get the Enter/Click command to work?

My code is as follows:

```
from pywebostv.discovery import *    
from pywebostv.connection import *
from pywebostv.controls import *

store = {'client_key', '<_super_secret_key_>'}

client = WebOSClient("lgwebostv")
client.connect()

inp = InputControl(client)
inp.connect_input()

inp.enter()

inp.disconnect_input()
```

However, when I run this, I get the following output:
```
Traceback (most recent call last):
  File "lgtv.py", line 39, in <module>
    inp.connect_input()
  File "/Users/user/Developer/LGTV/pywebostv/lib/python3.7/site-packages/pywebostv/controls.py", line 382, in connect_input
    raise IOError("Unable to connect to mouse.")
OSError: Unable to connect to mouse.
```

The Wireshark capture of this transaction has the following coming back from the TV:
```
{"type":"error","id":"79db27fd-49e6-47ba-bdeb-41a3e6285708","error":"401 insufficient permissions (not registered)","payload":{}}
```

**Comment by supersaiyanmode** [comment]
As the error says, you haven't registered. Please re-read the steps in the readme file. Specifically, you have to iterate over the results of `client.register(store)`.

**Comment by Gustry** [comment]
Indeed `store` variable is not used in your script.
