### ISSUE TITLE
Feature Request - Turn Off Screen

### ISSUE THREAD

**Issue by heavenlyren** [supersaiyanmode/PyWebOSTV#61]
Hi there. Thanks for this SDK !
Is there a way to turn off the screen with it , like you can do in 'Energy Saving'  Menu where you can just turn the screen black by clicking  on 'Screen Off'

Side Request : 
Do you think it's possible to return the Name you set to the TV ? The 'Device Name' The System Info do not return that.

Thanks !

**Comment by jurekmroczkowski** [comment]
I came here just to write this feature request. Is it possible? Maybe with some indirect script that would manually press correct buttons?

**Comment by jurekmroczkowski** [comment]
It's definitely possible given that klattimer supports it:

>     def screenOff(self):
        self.__send_command("request", "ssap://com.webos.service.tvpower/power/turnOffScreen", {"standbyMode": "active"})

    def screenOn(self):
        self.__send_command("request", "ssap://com.webos.service.tvpower/power/turnOnScreen", {"standbyMode": "active"})

**Comment by supersaiyanmode** [comment]
Hi @jurekmroczkowski, Thank you so much!

I have just created a new PR #68 with the change. Can you folks please test it out?

**Comment by supersaiyanmode** [comment]
Checking in to see if anyone wants to test the patch out before I merge it with master. Cheers

**Comment by harlikodasma** [comment]
> Checking in to see if anyone wants to test the patch out before I merge it with master. Cheers

Tested it manually, works perfectly fine.

**Comment by supersaiyanmode** [comment]
Thank you so much! I almost forgot about this PR. Merging this in.

**Comment by harlikodasma** [comment]
> Thank you so much! I almost forgot about this PR. Merging this in.

Could you also update the pip package, please? Thanks!

**Comment by supersaiyanmode** [comment]
Done. Updated PyPI, the latest version is v0.8.7.
