### ISSUE TITLE
Prompt each time I relaunch my remote

### ISSUE THREAD

**Issue by Gustry** [supersaiyanmode/PyWebOSTV#8]
I have no idea how the security is done in this remote, but the script is still asking me the prompt on TV when I relaunch my script. Is there a trick to do to avoid this?

I can update the readme if needed. (I have another PR coming)

**Comment by supersaiyanmode** [comment]
That is why there's a 'store' variable in the README. It's meant to be persisted somewhere (DB, config file) and re-read into before the second use.

**Comment by supersaiyanmode** [comment]
BTW, thanks for pointing out! I have fixed the README. :)
