### ISSUE TITLE
Request for write access to repo

### ISSUE THREAD

**Issue by jo47011** [supersaiyanmode/PyWebOSTV#85]
Hi @supersaiyanmode,

great & easy access to the LG TV.  Thanks for that 😄 

I enhanced my copy so notifications also support for icons (optional).  If you want these changes in your repo I need write access to create a PR.  Currently I get:
`remote: Permission to supersaiyanmode/PyWebOSTV.git denied to jo47011.`

**Comment by Gustry** [comment]
You should push to your **own** fork, then you submit the PR from your fork on this repository ;-)

**Comment by supersaiyanmode** [comment]
Thanks so much for looking to contribute. Can you please create a PR (Pull Request) in order to contribue? You might find this [tutorial useful](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

**Comment by jo47011** [comment]
Understood.  Thanks for the details on howto create a PR.
Here it is: https://github.com/supersaiyanmode/PyWebOSTV/pull/86
