### ISSUE TITLE
NameError: name 'your_custom_storage_is_empty' is not defined

### ISSUE THREAD

**Issue by Dirki74** [supersaiyanmode/PyWebOSTV#90]
I tried to come in into your Really nicht piece of Code, but i get following error, running this code:

http://schnippsel.de/paste.php?id=4467

**Comment by Gustry** [comment]
This is somehow expected.

`your_custom_storage_is_empty` is designed to be replaced by your own custom function to retrieve/store the token given by the TV. You need to adapt the code.

PyWebOSTV is a library for communicating with the TV, it's up to you to choose what you want to do with the token, store in a file, store in a database etc ...
