### ISSUE TITLE
[Question] How do the cursor socket messages look?

### ISSUE THREAD

**Issue by Sucharek233** [supersaiyanmode/PyWebOSTV#94]
I'm trying to remake this in c++ with a ui (qt) and everything so far except the the cursor socket. I can connect to the socket, but just can't figure out what to send. I tried debugging your code and the output was this (converted to json): `{type:"button", "name":"INFO"}`. I tried to send that exact thing to the socket, but nothing happened. I also tried putting it in `payload{...}` or putting in the `client-key`, but nothing just worked.
Could you tell me what exactly you're sending to the cursor socket? Thanks

**Comment by supersaiyanmode** [comment]
Does this help: https://github.com/supersaiyanmode/PyWebOSTV/discussions/54?

**Comment by Sucharek233** [comment]
Yes, it works now. I thought the message was in JSON format, but it wasn't. I also didn't get it to work right away, but fixed it by adding 2 newlines at the end (for example `type:button\nname:INFO\n\n`.
Thank you for helping.
