### ISSUE TITLE
YouTube launchs, but not start the video given by content_id

### ISSUE THREAD

**Issue by Koschi2015** [supersaiyanmode/PyWebOSTV#99]
Hello supersaiyanmode,

just found your lib, great work thank you for this.

I try your YouTube snipped, but it only launchs YouTube and don't start playing the video.
The contend_id is a valid youTube content string (for example SNTHqiN_tXM)

Do you have any advice for me?

Trying on:
Model: 55UP7009FL
webOS Version: 6.3.3-439

**Comment by supersaiyanmode** [comment]
Hmm, this looks like Youtube might have changed its internals around how it handles these arguments. Can you maybe try the full URL?

**Comment by Koschi2015** [comment]
I tried, the screen changed. instead of youTube start-screen my TV showed me big YouTube logo and a spinning circle but after 5 min the circle is still spinning.

I tried also video link for example: https://youtu.be/HwYy3xK5lvI (instead of URL:https://www.youtube.com/watch?v=HwYy3xK5lvI)
Both did not work.

Why do you think they change internal handle with this argument? Did you also check it and got same result?

**Comment by supersaiyanmode** [comment]
Hi sorry, I am not around an LG TV. But, yes, this used to work before, and if it doesn't work now, it implies it would be broken for everyone -- Unless other similar libraries are able to do it, but not this one.

**Comment by Koschi2015** [comment]
YES! finally i found the solution.

The last line in this readme here https://github.com/webosbrew/youtube-webos gave me the idea for the solution.
the contend_id must start with "v=" + videoID.

**Comment by supersaiyanmode** [comment]
Brilliant! Would you like to send a PR to update the README in this repo?

**Comment by Koschi2015** [comment]
I never did one, but I will try when I am home.
